In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2,3),124)

array([[124, 124, 124],
       [124, 124, 124]])

In [8]:
"""
np.arange(start,stop,end)-----> returns an numpy array
"""
print(np.arange(1,11,2))


[1 3 5 7 9]


In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr=np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(2, 3)
6


In [11]:
"""
converting one type of numpy array to another type
.astype(data_type)
"""

arr=np.array(['12','13','14'])
arr=arr.astype(int)
print(arr)

[12 13 14]


In [12]:
"""
arithmetic operations on numpy array
"""
np_array=np.array([1,2,3,4,5])
print(np_array+2)
print(np_array-2)
print(np_array*4)
print(np_array/2)
print(np_array//2)
print(np_array%3)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 4  8 12 16 20]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[1 2 0 1 2]


In [13]:
"""
application of statistics on numpy array
"""
np_array=np.array([1,2,3,4,5,6,7,8,9,12])
print(np.sum(np_array))
print(np.min(np_array))
print(np.max(np_array))
print(np.mean(np_array))
print(np.std(np_array))
print(np.median(np_array))

print(np_array[[0,3,4]])

57
1
12
5.7
3.2264531609803355
5.5
[1 4 5]


In [14]:
"""
boolean masking of numpy array
"""

np_array=np.array([142,122,110,108,145,165,98,34])
print(np_array>132)

[ True False False False  True  True False False]


In [15]:
"""
.reshape((row,col)) ----> we have to maintain the shape
it creates a view of the original array..so any change in the view 
will also reflect on the main array
"""

np_arr=np.array([[1,2,3,4],[12,13,14,15],[21,22,23,24]])
print(np_arr)
np_arr2=np_arr.reshape((6,2))
print(np_arr2)
np_arr2[2,0]=-124
print(np_arr)

[[ 1  2  3  4]
 [12 13 14 15]
 [21 22 23 24]]
[[ 1  2]
 [ 3  4]
 [12 13]
 [14 15]
 [21 22]
 [23 24]]
[[   1    2    3    4]
 [-124   13   14   15]
 [  21   22   23   24]]


In [16]:
"""
array flattening means converting multi dimensional array
into 1D array
.ravel() ----> it creates a view of the main array
.flatten() ---> it creates a copy of the main array
"""

arr_2d=np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)
print(arr_2d)
arr1=arr_2d.ravel()
print(arr1)
arr2=arr_2d.flatten()
print(arr2)
arr2[2]=-123
print(arr2)
print(arr_2d)
arr1[2]=-123
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[   1    2 -123    4    5    6    7    8]
[[1 2 3 4]
 [5 6 7 8]]
[[   1    2 -123    4]
 [   5    6    7    8]]


In [17]:
"""
to insert an element in the numpy array
np.insert(array,index,value,axis)
array ---> our main array
index ---> the index at which we want to insert a new element
value ---> the value we want to insert
axis ----> axis=0 means row wise,axis=1 means column wise
"""

arr=np.array([10,12,15,17,19,21])
new_arr=np.insert(arr,3,-124,axis=None)
print(new_arr)

[  10   12   15 -124   17   19   21]


In [18]:
arr_2D=np.array([[1,2,3,4],[12,13,14,15],[198,199,200,201]])
new_arr_2D=np.insert(arr_2D,1,[2,21,121,1212],axis=0)
print(new_arr_2D)

new_arr_2D = np.insert(arr_2D, 2, [[124], [124], [124]], axis=1)
print(new_arr_2D)

[[   1    2    3    4]
 [   2   21  121 1212]
 [  12   13   14   15]
 [ 198  199  200  201]]
[[  1   2 124 124 124   3   4]
 [ 12  13 124 124 124  14  15]
 [198 199 124 124 124 200 201]]


In [19]:
"""
np.append() ---> to add an element,row or column in the numpy array
"""
np_array=np.array([1,2,3,4,5,6])
print(np_array)
np_array=np.append(np_array,[123,124,125],axis=None)
print(np_array)

[1 2 3 4 5 6]
[  1   2   3   4   5   6 123 124 125]


In [20]:
np_array=np.array([[1,3,4],[12,13,14],[56,57,58]])
print(np_array)
np_array=np.append(np_array,[[-1,-2,-3]],axis=0)
print(np_array)
np_array=np.append(np_array,[[-124],[-125],[-125],[-126]],axis=1)
print(np_array)

[[ 1  3  4]
 [12 13 14]
 [56 57 58]]
[[ 1  3  4]
 [12 13 14]
 [56 57 58]
 [-1 -2 -3]]
[[   1    3    4 -124]
 [  12   13   14 -125]
 [  56   57   58 -125]
 [  -1   -2   -3 -126]]


In [21]:
"""
np.concatenate((a1,a2),axis)
axis=0 ----> horizontal stacking
axis=1 ----> vertical stacking
"""

a1=np.array([1,2,3])
a2=np.array([4,5,6])
new_arr=np.concatenate((a1,a2),axis=0)
print(new_arr)
a1=np.array(
    [
        [1,2],
        [3,4]
    ]
)
a2=np.array(
    [
        [121,123],
        [124,125]
    ]
)

new_arr=np.concatenate((a1,a2),1)
print(new_arr)


[1 2 3 4 5 6]
[[  1   2 121 123]
 [  3   4 124 125]]


In [22]:
"""
to delete an element from the numpy array we use np.delete()
np.delete(array,index,axis)
"""
a1=np.array([1,2,3,4,5,6])
a1=np.delete(a1,2)
print(a1)

[1 2 4 5 6]


In [23]:
a1=np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
a1=np.delete(a1,0,axis=0)
print(a1)
a1=np.delete(a1,0,axis=1)
print(a1)

[[4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


In [24]:
"""
to combine two numpy arrays we use
np.vstack() ----> for vertical stacking
np.hstack() ----> for horizontal stacking
"""

a1=np.array([[1,2,3,4],[124,125,126,127]])
a2=np.array([[-1,-2,-3,-4],[-7,-8,-9,-10]])
a3=np.vstack((a1,a2))
a4=np.stack((a1,a2))
print(a3)
print(a4)

[[  1   2   3   4]
 [124 125 126 127]
 [ -1  -2  -3  -4]
 [ -7  -8  -9 -10]]
[[[  1   2   3   4]
  [124 125 126 127]]

 [[ -1  -2  -3  -4]
  [ -7  -8  -9 -10]]]


In [25]:
"""
to split an array into two equal parts
np.split()

to split horizontally we use np.hsplit()
to split vertically we use np.vsplit()
"""

arr=np.array([1,2,3,4,5,6])
print(np.split(arr,2))
print(np.split(arr,3))
# print(np.split(arr,4))

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [26]:
"""
to combine two numpy array we use
np.vstack() ------> for vertical stacking
np.hstack() ------> for horizontal stacking
"""

a1=np.array([[1,2,3,4],[124,125,126,127]])
a2=np.array([[12,13,14,15],[21,22,23,24]])
a3=np.vstack((a1,a2))
print(a3)
a4=np.hstack((a1,a2))
print(a4)

[[  1   2   3   4]
 [124 125 126 127]
 [ 12  13  14  15]
 [ 21  22  23  24]]
[[  1   2   3   4  12  13  14  15]
 [124 125 126 127  21  22  23  24]]


In [27]:
# to get the size of the each item of the array
print(a4.itemsize)
# to get the total memeory
print(a4.nbytes)

8
128


In [28]:
# to get a specific element from numpy arrray [r,c]
print(a1[1,3])
print(a1[:,2:4])

127
[[  3   4]
 [126 127]]


In [29]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[124,125,126,127,128,129,130],[-1,-2,-3,-4,-5,-6,-7],[-12,-13,-14,-15,-16,-17,-18]])
print(a[:3:2,:4:2])
print(a[1,:])
print(a[:,1])

[[  1   3]
 [124 126]]
[ 8  9 10 11 12 13 14]
[  2   9 125  -2 -13]


In [30]:
a[1,3:5]=[-1000,1000]
print(a)
a[2,:6:2]=[-70,-80,-90]
print(a)

[[    1     2     3     4     5     6     7]
 [    8     9    10 -1000  1000    13    14]
 [  124   125   126   127   128   129   130]
 [   -1    -2    -3    -4    -5    -6    -7]
 [  -12   -13   -14   -15   -16   -17   -18]]
[[    1     2     3     4     5     6     7]
 [    8     9    10 -1000  1000    13    14]
 [  -70   125   -80   127   -90   129   130]
 [   -1    -2    -3    -4    -5    -6    -7]
 [  -12   -13   -14   -15   -16   -17   -18]]


In [31]:
a=np.array([[2,3,4],[12,13,14]])
print(a)
b=np.full_like(a,12)
print(b)

[[ 2  3  4]
 [12 13 14]]
[[12 12 12]
 [12 12 12]]


In [32]:
"""
to fill an array with random decimal numbers
np.random.rand()
"""

a=np.random.rand(2,3)
print(a)

[[0.525974   0.18128476 0.33282458]
 [0.92602882 0.36671311 0.35276716]]


In [33]:
a=np.random.randint(0,13,(2,3))
print(a)

[[ 6 12  0]
 [ 9  6  1]]


In [34]:
# to repeat an array
a=np.array([1,2,3])
b=np.repeat(a,4,axis=0)
print(b)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [35]:
a=np.array([[1,2,3]])
b=np.repeat(a,3,axis=0)
print(b)
b=np.repeat(a,3,axis=1)
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [36]:
"""
be carefull of copying numpy arrays.....they are copied as reference
any change in the copied array will also reflect in the main array
"""
a=np.array([1,2,3])
b=a
b[1]=123
print(a)
b=a.copy()
b[1]=145
print(a)

[  1 123   3]
[  1 123   3]


In [37]:
"""
we can apply trigonometric functions on numpy array
"""
a=np.array([0,np.pi/6,np.pi/4,np.pi/3,np.pi/2])
print(np.sin(a))
print(np.cos(a))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [38]:
"""
we can do all sorts of linear algebra calculations using numpy array
"""
a1=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(a1.shape)
a2=np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(a2.shape)
ans=np.matmul(a1,a2)
print(ans)

(3, 3)
(3, 2)
[[ 22  28]
 [ 49  64]
 [ 76 100]]


In [39]:
c=np.identity(3)
print(np.linalg.det(c))

1.0


In [40]:
a=np.array([
    [1,1],
    [1,2]
])
inv_a=np.linalg.inv(a)
print(inv_a)

[[ 2. -1.]
 [-1.  1.]]


In [41]:
"""
broadcasting in numpy arrays
it is basically applying some conditions on the whole array
without using any loops
three conditions
1.matching dimensions
2.expanding single elements
a1=np.array([10,20,30])
print(a1+10) ----> here 10 is considered as [10,10,10]
3.incompatable shapes ----> if the shapes are different then numpy will
throw an error
"""

price=np.array([100,200,300])
final_price=price-(price*10/100)
print(final_price)
arr=np.array([10,20,30])
print(arr*2)
matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([10,20,30])
vector2=np.array([10,20])
result=matrix+vector
print(result)
# result=matrix+vector2
# print(result)

[ 90. 180. 270.]
[20 40 60]
[[11 22 33]
 [14 25 36]]


In [42]:
"""
handling the missing values using numpy arrays
np.isnan() ----> to detect missing values
np.nan_to_num() ----> converting the missing values to another number
np.isinf() -----> to detect the infinite values
"""

"""
NAN ----> Not a Number
"""

arr=np.array([1,2,np.nan,4,np.nan,6])
print(arr)
print(np.isnan(arr))
print(np.nan_to_num(arr,nan=0))
print(np.nan_to_num(arr,nan=-1))

[ 1.  2. nan  4. nan  6.]
[False False  True False  True False]
[1. 2. 0. 4. 0. 6.]
[ 1.  2. -1.  4. -1.  6.]


In [43]:
arr=np.array([1,2,np.inf,3,4,-np.inf])
print(arr)
print(np.isinf(arr))
print(np.nan_to_num(arr,posinf=100,neginf=-100))

[  1.   2.  inf   3.   4. -inf]
[False False  True False False  True]
[   1.    2.  100.    3.    4. -100.]


In [44]:
"""
np.diag() function is used to extract the diagonal values from a matrix
"""
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b=np.diag(a)
print(b)
a=np.array([10,20,30])
b=np.diag(a)
print(b)
c=np.array([1,2,3])
print(c)
d=np.diag(c)
print(d)
d=np.diag(c)+np.diag([-1,-2],k=1)
print(d)


[1 5 9]
[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[ 1 -1  0]
 [ 0  2 -2]
 [ 0  0  3]]


In [45]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.diag(a)
print(b)

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


In [46]:
c=np.array([-1,-2,-3,-4,-5,-6,-7,-8,-9])
b=b+np.diag(c,k=1)
print(b)

[[ 1 -1  0  0  0  0  0  0  0  0]
 [ 0  2 -2  0  0  0  0  0  0  0]
 [ 0  0  3 -3  0  0  0  0  0  0]
 [ 0  0  0  4 -4  0  0  0  0  0]
 [ 0  0  0  0  5 -5  0  0  0  0]
 [ 0  0  0  0  0  6 -6  0  0  0]
 [ 0  0  0  0  0  0  7 -7  0  0]
 [ 0  0  0  0  0  0  0  8 -8  0]
 [ 0  0  0  0  0  0  0  0  9 -9]
 [ 0  0  0  0  0  0  0  0  0 10]]


In [47]:
d=np.array([100,200,300,400,500,600,700,800,900])
b=b+np.diag(d,k=-1)
print(b)

[[  1  -1   0   0   0   0   0   0   0   0]
 [100   2  -2   0   0   0   0   0   0   0]
 [  0 200   3  -3   0   0   0   0   0   0]
 [  0   0 300   4  -4   0   0   0   0   0]
 [  0   0   0 400   5  -5   0   0   0   0]
 [  0   0   0   0 500   6  -6   0   0   0]
 [  0   0   0   0   0 600   7  -7   0   0]
 [  0   0   0   0   0   0 700   8  -8   0]
 [  0   0   0   0   0   0   0 800   9  -9]
 [  0   0   0   0   0   0   0   0 900  10]]


In [48]:
"""
to get the index of any specific element of a matrix
we use unravel_index(index,shape) function
np.unravel_index(index,shape)
"""

print(np.unravel_index(6,(2,2,2)))
a=np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [4,5],
        [6,7]
    ]
])
print(a[1,1,0])



(1, 1, 0)
6


In [49]:
"""
to repeat an array we use tile function
np.tile(array,reps)

.repeat() function repeats the elements not the whole array
"""

a=np.array([1,2,3])
b=np.tile(a,3)
print(b)
a=np.array([
    [1,2],
    [3,4]
])
print(a)
b=np.tile(a,(2,3)) # (2,3) ----> vertically twice and horizontally thrice
print(b)

[1 2 3 1 2 3 1 2 3]
[[1 2]
 [3 4]]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]
